### ISSUE TITLE
Can not open dataset url

### ISSUE THREAD

**Issue by jianlong-yuan** [csyanbin/SCOT#2]
Hi, https://docs.google.com/uc?export=download  how to open this url?

**Comment by csyanbin** [comment]
Please run data/download.py to download the corresponding dataset.

**Comment by nihaomiao** [comment]
Hi, @csyanbin , I try to download those datasets but it seems that those file id can't work (just get 404 response). Could you directly give me the link of google drive? Thanks a lot!

**Comment by csyanbin** [comment]
Hi @jianlong-yuan @nihaomiao ,

I have updated the download link, please check and download again.

**Comment by nihaomiao** [comment]
@csyanbin It works now! Thanks a lot!
